name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
        value: |
            Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
        label: Bug Description
    description: Please give us a high-level description of your bug
    placeholder: Enter here a high-level description of your bug.
    value: "description"
    validations:
        required: true
  - type: textarea
    id: example
    attributes:
        label: Minimal, reproducible example
    description: Please give us a minimal, reproducible example of your bug
    placeholder: Enter here a minimal, reproducible example of your bug.
    value: "example"
    validations:
        required: true
  - type: textarea
    id: sessioninfo
    attributes:
        label: Session info
    description: Please enter the results of `xfun::session_info("ggpattern")`
    placeholder: Enter here the results of `xfun::session_info("ggpattern")`.
    value: "session"
    validations:
        required: true
