blank_issues_enabled: false
contact_links:
    - name: Questions
      url: https://stackoverflow.com/questions/tagged/r
      about: Please ask and answer questions at Stack Overflow.  Please add "ggpattern" (and "ggplot2") tags.
